package com.nicname.iyeongjun.dobike.api.model.forecast

import com.google.gson.annotations.SerializedName

data class Precipitation(
    @SerializedName("type4hour") val type4hour: String,
    @SerializedName("prob4hour") val prob4hour: String,
    @SerializedName("type7hour") val type7hour: String,
    @SerializedName("prob7hour") val prob7hour: String,
    @SerializedName("type10hour") val type10hour: String,
    @SerializedName("prob10hour") val prob10hour: String,
    @SerializedName("type13hour") val type13hour: String,
    @SerializedName("prob13hour") val prob13hour: String,
    @SerializedName("type16hour") val type16hour: String,
    @SerializedName("prob16hour") val prob16hour: String,
    @SerializedName("type19hour") val type19hour: String,
    @SerializedName("prob19hour") val prob19hour: String,
    @SerializedName("type22hour") val type22hour: String,
    @SerializedName("prob22hour") val prob22hour: String,
    @SerializedName("type25hour") val type25hour: String,
    @SerializedName("prob25hour") val prob25hour: String,
    @SerializedName("type28hour") val type28hour: String,
    @SerializedName("prob28hour") val prob28hour: String,
    @SerializedName("type31hour") val type31hour: String,
    @SerializedName("prob31hour") val prob31hour: String,
    @SerializedName("type34hour") val type34hour: String,
    @SerializedName("prob34hour") val prob34hour: String,
    @SerializedName("type37hour") val type37hour: String,
    @SerializedName("prob37hour") val prob37hour: String,
    @SerializedName("type40hour") val type40hour: String,
    @SerializedName("prob40hour") val prob40hour: String,
    @SerializedName("type43hour") val type43hour: String,
    @SerializedName("prob43hour") val prob43hour: String,
    @SerializedName("type46hour") val type46hour: String,
    @SerializedName("prob46hour") val prob46hour: String,
    @SerializedName("type49hour") val type49hour: String,
    @SerializedName("prob49hour") val prob49hour: String,
    @SerializedName("type52hour") val type52hour: String,
    @SerializedName("prob52hour") val prob52hour: String,
    @SerializedName("type55hour") val type55hour: String,
    @SerializedName("prob55hour") val prob55hour: String,
    @SerializedName("type58hour") val type58hour: String,
    @SerializedName("prob58hour") val prob58hour: String,
    @SerializedName("type61hour") val type61hour: String,
    @SerializedName("prob61hour") val prob61hour: String,
    @SerializedName("type64hour") val type64hour: String,
    @SerializedName("prob64hour") val prob64hour: String,
    @SerializedName("type67hour") val type67hour: String,
    @SerializedName("prob67hour") val prob67hour: String
)