package com.nicname.iyeongjun.dobike.api.model.forecast

import com.google.gson.annotations.SerializedName

data class Sky(
        @SerializedName("code4hour") val code4hour: String,
        @SerializedName("name4hour") val name4hour: String,
        @SerializedName("code7hour") val code7hour: String,
        @SerializedName("name7hour") val name7hour: String,
        @SerializedName("code10hour") val code10hour: String,
        @SerializedName("name10hour") val name10hour: String,
        @SerializedName("code13hour") val code13hour: String,
        @SerializedName("name13hour") val name13hour: String,
        @SerializedName("code16hour") val code16hour: String,
        @SerializedName("name16hour") val name16hour: String,
        @SerializedName("code19hour") val code19hour: String,
        @SerializedName("name19hour") val name19hour: String,
        @SerializedName("code22hour") val code22hour: String,
        @SerializedName("name22hour") val name22hour: String,
        @SerializedName("code25hour") val code25hour: String,
        @SerializedName("name25hour") val name25hour: String,
        @SerializedName("code28hour") val code28hour: String,
        @SerializedName("name28hour") val name28hour: String,
        @SerializedName("code31hour") val code31hour: String,
        @SerializedName("name31hour") val name31hour: String,
        @SerializedName("code34hour") val code34hour: String,
        @SerializedName("name34hour") val name34hour: String,
        @SerializedName("code37hour") val code37hour: String,
        @SerializedName("name37hour") val name37hour: String,
        @SerializedName("code40hour") val code40hour: String,
        @SerializedName("name40hour") val name40hour: String,
        @SerializedName("code43hour") val code43hour: String,
        @SerializedName("name43hour") val name43hour: String,
        @SerializedName("code46hour") val code46hour: String,
        @SerializedName("name46hour") val name46hour: String,
        @SerializedName("code49hour") val code49hour: String,
        @SerializedName("name49hour") val name49hour: String,
        @SerializedName("code52hour") val code52hour: String,
        @SerializedName("name52hour") val name52hour: String,
        @SerializedName("code55hour") val code55hour: String,
        @SerializedName("name55hour") val name55hour: String,
        @SerializedName("code58hour") val code58hour: String,
        @SerializedName("name58hour") val name58hour: String,
        @SerializedName("code61hour") val code61hour: String,
        @SerializedName("name61hour") val name61hour: String,
        @SerializedName("code64hour") val code64hour: String,
        @SerializedName("name64hour") val name64hour: String,
        @SerializedName("code67hour") val code67hour: String,
        @SerializedName("name67hour") val name67hour: String
)