package com.nicname.iyeongjun.dobike.api.model.forecast

import com.google.gson.annotations.SerializedName

data class Wind(
        @SerializedName("wdir4hour") val wdir4hour: String,
        @SerializedName("wspd4hour") val wspd4hour: String,
        @SerializedName("wdir7hour") val wdir7hour: String,
        @SerializedName("wspd7hour") val wspd7hour: String,
        @SerializedName("wdir10hour") val wdir10hour: String,
        @SerializedName("wspd10hour") val wspd10hour: String,
        @SerializedName("wdir13hour") val wdir13hour: String,
        @SerializedName("wspd13hour") val wspd13hour: String,
        @SerializedName("wdir16hour") val wdir16hour: String,
        @SerializedName("wspd16hour") val wspd16hour: String,
        @SerializedName("wdir19hour") val wdir19hour: String,
        @SerializedName("wspd19hour") val wspd19hour: String,
        @SerializedName("wdir22hour") val wdir22hour: String,
        @SerializedName("wspd22hour") val wspd22hour: String,
        @SerializedName("wdir25hour") val wdir25hour: String,
        @SerializedName("wspd25hour") val wspd25hour: String,
        @SerializedName("wdir28hour") val wdir28hour: String,
        @SerializedName("wspd28hour") val wspd28hour: String,
        @SerializedName("wdir31hour") val wdir31hour: String,
        @SerializedName("wspd31hour") val wspd31hour: String,
        @SerializedName("wdir34hour") val wdir34hour: String,
        @SerializedName("wspd34hour") val wspd34hour: String,
        @SerializedName("wdir37hour") val wdir37hour: String,
        @SerializedName("wspd37hour") val wspd37hour: String,
        @SerializedName("wdir40hour") val wdir40hour: String,
        @SerializedName("wspd40hour") val wspd40hour: String,
        @SerializedName("wdir43hour") val wdir43hour: String,
        @SerializedName("wspd43hour") val wspd43hour: String,
        @SerializedName("wdir46hour") val wdir46hour: String,
        @SerializedName("wspd46hour") val wspd46hour: String,
        @SerializedName("wdir49hour") val wdir49hour: String,
        @SerializedName("wspd49hour") val wspd49hour: String,
        @SerializedName("wdir52hour") val wdir52hour: String,
        @SerializedName("wspd52hour") val wspd52hour: String,
        @SerializedName("wdir55hour") val wdir55hour: String,
        @SerializedName("wspd55hour") val wspd55hour: String,
        @SerializedName("wdir58hour") val wdir58hour: String,
        @SerializedName("wspd58hour") val wspd58hour: String,
        @SerializedName("wdir61hour") val wdir61hour: String,
        @SerializedName("wspd61hour") val wspd61hour: String,
        @SerializedName("wdir64hour") val wdir64hour: String,
        @SerializedName("wspd64hour") val wspd64hour: String,
        @SerializedName("wdir67hour") val wdir67hour: String,
        @SerializedName("wspd67hour") val wspd67hour: String
)